//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Downtown_Alley_Integrated_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string ItemName { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Materials { get; set; }
        public Nullable<System.DateTime> DatetimeAdded { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
