//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Downtown_Alley_Integrated_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int ReceiptID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<System.DateTime> ReceiptDataTime { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> TotalAmountWithVat { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
